services:
  - type: web
    name: rest-express-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: rest-express-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: rest-express-db
    databaseName: restexpress
    user: restexpress
    plan: free